---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Launchpad
 - Facetime
 - Messages
 - Maps
 - Contacts
 - Podcasts
 - TV

dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - ffmpeg
  - nmap
  - ssh-copy-id
  - openssl
  - wget
  - tmux
  - sshuttle
  - organize-tool
  - bitwarden-cli
  - koekeishiya/formulae/yabai
  - koekeishiya/formulae/skhd
  - yadm
  - rancher-cli
  - tailscale
  - fzf
  - svn
  - jq 
  - MisterTea/et/et
  - tmuxp

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alt-tab
  - barrier
  - caffeine
  - cyberduck
  - copyq
  - drawio
  - discord
  - espanso
  - firefox
  - google-chrome
  - iterm2
  - joplin
  - karabiner-elements
  - maccy
  - microsoft-excel
  - microsoft-powerpoint
  - microsoft-teams
  - microsoft-word
  - mqtt-explorer
  - monitorcontrol
  - numi
  - obs
  - onedrive
  - rar
  - skype
  - steermouse
  - spotify
  - tunnelblick
  - visual-studio-code
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 1473726602, name: "Tab Space" }
  - { id: 747648890, name: "Telegram" }
  - { id: 1147396723, name: "Whatsapp" }
  - { id: 405399194, name: "Kindle" }  

