---
  - name: Install Oh My ZSH
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    args:
      creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

  - name: clone zsh-autosuggestions 
    git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      version: master
      dest: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

  - name: Install Powerlevel10k
    shell: sh -c "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
    args:
      creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/themes/powerlevel10k"
     
  - name: Install Oh My Tmux
    shell: sh -c "cd ~; git clone https://github.com/gpakosz/.tmux.git"
    args:
      creates: "/Users/{{ lookup('env', 'USER') }}/.tmux/.tmux.conf"
     
  - name: Link the oh-my-tmux default conf
    ansible.builtin.file:
      src: "/Users/{{ lookup('env', 'USER') }}/.tmux/.tmux.conf"
      dest:  "/Users/{{ lookup('env', 'USER') }}/.tmux.conf"
      state: link

